# Generated by Django 4.0.5 on 2022-07-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
