# Generated by Django 4.0.5 on 2022-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('ACCEPTED', 'Accepted'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(null=True),
        ),
    ]
